#ifndef ISM330DHCX_UTILS_H_
#define ISM330DHCX_UTILS_H_

typedef enum {
    OK = 0,
    ERROR = 1,
} ISM330DHCX_Status;

typedef enum {
    ACCELEROMETAR_RANGE_2G  = 0,
    ACCELEROMETAR_RANGE_4G  = 1,
    ACCELEROMETAR_RANGE_8G  = 2,
    ACCELEROMETAR_RANGE_16G = 3
} ACCELEROMETAR_RANGE;

typedef enum {
    GYROSCOPE_RANGE_125DPS  = 0,
    GYROSCOPE_RANGE_250DPS  = 1,
    GYROSCOPE_RANGE_500DPS  = 2,
    GYROSCOPE_RANGE_1000DPS = 3,
    GYROSCOPE_RANGE_2000DPS = 4,
    GYROSCOPE_RANGE_4000DPS = 5
} GYROSCOPE_RANGE;

#endif